# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5c422d5a89c44c5a908ca157a76d1de6e7759e3da0aa0639b46aabd5f38214240adee8432b09b45468d3f517fc91262b06eea55c86b76386a1b4cc3082161be9

test:
  secret_key_base: 19d2e00a18b57c0629166298050c8fb4cae905a074d25c83cfda432d5542cde13ba1075665b0917359281b5047e1d8857a965cdcc485c5c9fff643275a1f6c8b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
